on: [workflow_dispatch]
name: Build Angular
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: npm install and npm run build
        run: |
          npm i
          npm run build
      - name: Zip dist files
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'release.zip'
          directory: 'dist/tex-cards'
      - name: Push Build to Releases
        uses: ncipollo/release-action@v1
        with:
          tag: "v1.0"
          artifacts: "dist/tex-cards/release.zip"
          token: ${{ secrets.TOKEN }}
